import { Opportunity, StudentProfile, StrategyOutput } from './types';

export const mockProfile: StudentProfile = {
  id: 'student-1',
  name: 'Priya Sharma',
  email: 'priya@university.edu',
  major: 'Computer Science',
  school: 'University of Illinois Urbana-Champaign',
  degreeLevel: 'Master',
  graduationDate: '2025-05-15',
  gpa: 3.8,
  currentVisa: 'F-1 (OPT)',
  optStartDate: '2025-06-01',
  stemEligible: true,
  sponsorshipNeeded: true,
  engineeringDiscipline: 'Software/CS',
  roleFamilyPreferences: ['internship', 'entry-level', 'co-op'],
  tools: ['GitHub', 'Jira', 'VS Code', 'Figma'],
  targetRoles: ['Software Engineer', 'ML Engineer', 'Data Scientist'],
  targetIndustries: ['Technology', 'FinTech', 'AI/ML'],
  skills: ['Python', 'TypeScript', 'React', 'PyTorch', 'AWS', 'SQL'],
  experienceLevel: 'Entry Level',
  preferredLocations: ['San Francisco, CA', 'Seattle, WA', 'New York, NY'],
  remotePreference: 'Hybrid',
  yearsOfExperience: 1,
};

export const mockOpportunities: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'Software Engineer II',
    company: 'Microsoft',
    companyInitials: 'MS',
    companyColor: '#0078d4',
    location: 'Seattle, WA',
    remote: false,
    salaryRange: '$130k – $165k',
    matchScore: 94,
    fitTier: 'Realistic',
    sponsorshipStatus: 'Strong History',
    cptCompatible: true,
    optCompatible: true,
    h1bSponsor: true,
    matchReasons: [
      '8+ consecutive years of H-1B sponsorship',
      'MS in CS aligns with role requirements',
      'Strong Python and TypeScript fit',
      'Seattle is your top preferred location',
    ],
    warningFlags: [],
    recommendedAction: 'Apply immediately — this is your highest-confidence match.',
    postedDate: '2025-04-12',
    industry: 'Technology',
    experienceRequired: 'Entry Level',
    skills: ['TypeScript', 'Python', 'Azure', 'React'],
    description: 'Join a core product engineering team building tools used by millions.',
    applicants: 340,
    engineeringDiscipline: 'Software/CS',
    roleFamily: 'entry-level',
  },
  {
    id: 'opp-2',
    title: 'ML Engineer',
    company: 'Google',
    companyInitials: 'G',
    companyColor: '#4285f4',
    location: 'San Francisco, CA',
    remote: false,
    salaryRange: '$155k – $210k',
    matchScore: 88,
    fitTier: 'Realistic',
    sponsorshipStatus: 'Strong History',
    cptCompatible: false,
    optCompatible: true,
    h1bSponsor: true,
    matchReasons: [
      'Top H-1B sponsor — sponsored 3,200+ in 2024',
      'PyTorch experience is a strong match',
      'STEM OPT eligibility extends runway by 2 years',
      'Engineering discipline: Data/AI/ML',
    ],
    warningFlags: ['Highly competitive — 1,200+ applicants expected'],
    recommendedAction:
      'Tailor your resume toward ML infrastructure work. Referral highly recommended.',
    postedDate: '2025-04-10',
    industry: 'Technology',
    experienceRequired: 'Entry Level',
    skills: ['Python', 'PyTorch', 'TensorFlow', 'Kubernetes'],
    description:
      "Work on ML systems that power Google's core search and ads infrastructure.",
    applicants: 1240,
    engineeringDiscipline: 'Data/AI/ML',
    roleFamily: 'entry-level',
  },
  {
    id: 'opp-3',
    title: 'Software Engineer Intern — Summer 2025',
    company: 'Stripe',
    companyInitials: 'ST',
    companyColor: '#635bff',
    location: 'San Francisco, CA',
    remote: true,
    salaryRange: '$8k – $10k/month',
    matchScore: 85,
    fitTier: 'Realistic',
    sponsorshipStatus: 'Strong History',
    cptCompatible: true,
    optCompatible: true,
    h1bSponsor: true,
    matchReasons: [
      'Internship role — CPT compatible',
      'FinTech aligns with your target industries',
      'SQL and Python are core requirements you meet',
      'Remote option suits flexible location preference',
    ],
    warningFlags: ['Interview process is rigorous — 5+ rounds'],
    recommendedAction: 'Strong internship fit. Prepare for system design questions.',
    postedDate: '2025-04-08',
    industry: 'FinTech',
    experienceRequired: 'Internship',
    skills: ['Python', 'SQL', 'TypeScript', 'React'],
    description: 'Help Stripe build the financial infrastructure of the internet.',
    applicants: 287,
    engineeringDiscipline: 'Software/CS',
    roleFamily: 'internship',
    sponsorshipSignal: 'Better',
  },
  {
    id: 'opp-4',
    title: 'Data Science Co-op',
    company: 'Airbnb',
    companyInitials: 'AB',
    companyColor: '#ff5a5f',
    location: 'San Francisco, CA',
    remote: true,
    salaryRange: '$7k – $9k/month',
    matchScore: 73,
    fitTier: 'Stretch',
    sponsorshipStatus: 'Occasional',
    cptCompatible: true,
    optCompatible: true,
    h1bSponsor: true,
    matchReasons: [
      'Co-op matches your role family preference',
      'Remote role fits your location preference',
    ],
    warningFlags: [
      'Sponsorship is not guaranteed — case-by-case basis',
      'Team prefers candidates with 1+ co-op experience',
    ],
    recommendedAction:
      "Worth applying. Ask about international student hiring policy in the recruiter screen.",
    postedDate: '2025-04-05',
    industry: 'Technology',
    experienceRequired: 'Internship',
    skills: ['Python', 'SQL', 'Statistics', 'dbt'],
    description:
      "Use data to improve Airbnb's host and guest experiences.",
    applicants: 520,
    engineeringDiscipline: 'Data/AI/ML',
    roleFamily: 'co-op',
  },
  {
    id: 'opp-5',
    title: 'Research Engineer Intern — LLM Safety',
    company: 'Anthropic',
    companyInitials: 'AN',
    companyColor: '#c96442',
    location: 'San Francisco, CA',
    remote: false,
    salaryRange: '$9k – $12k/month',
    matchScore: 70,
    fitTier: 'Stretch',
    sponsorshipStatus: 'Strong History',
    cptCompatible: true,
    optCompatible: true,
    h1bSponsor: true,
    matchReasons: [
      'Research internship — CPT compatible',
      'PyTorch and ML background is relevant',
    ],
    warningFlags: [
      'Role prefers PhD candidates or significant research experience',
      'Very competitive — publish or strong research background expected',
    ],
    recommendedAction:
      'Strong stretch. Highlight any published work or research projects in your application.',
    postedDate: '2025-04-01',
    industry: 'AI/ML',
    experienceRequired: 'Internship',
    skills: ['Python', 'PyTorch', 'Research', 'LLMs'],
    description:
      'Contribute to safety research on large language models and alignment.',
    applicants: 800,
    engineeringDiscipline: 'Research/Lab',
    roleFamily: 'research',
    sponsorshipSignal: 'Better',
  },
  {
    id: 'opp-6',
    title: 'Electrical Engineering Intern',
    company: 'Texas Instruments',
    companyInitials: 'TI',
    companyColor: '#c0392b',
    location: 'Dallas, TX',
    remote: false,
    salaryRange: '$25 – $35/hr',
    matchScore: 58,
    fitTier: 'Stretch',
    sponsorshipStatus: 'Occasional',
    cptCompatible: true,
    optCompatible: true,
    h1bSponsor: false,
    matchReasons: [
      'Internship role — CPT compatible',
      'Strong H-1B employer in semiconductor industry',
    ],
    warningFlags: [
      'No confirmed H-1B sponsorship in public records',
      'Engineering discipline mismatch: Electrical vs your Software/CS focus',
    ],
    recommendedAction:
      'Proceed only if you are open to hardware engineering roles. Verify sponsorship policy.',
    postedDate: '2025-03-28',
    industry: 'Semiconductor',
    experienceRequired: 'Internship',
    skills: ['MATLAB', 'FPGA', 'C++', 'Signal Processing'],
    description:
      'Design and test analog and mixed-signal circuits for power management ICs.',
    applicants: 410,
    engineeringDiscipline: 'Electrical/Hardware',
    roleFamily: 'internship',
  },
  {
    id: 'opp-7',
    title: 'Student Trainee (Engineering)',
    company: 'NASA Jet Propulsion Laboratory',
    companyInitials: 'JPL',
    companyColor: '#1a3a6b',
    location: 'Pasadena, CA',
    remote: false,
    salaryRange: '$22 – $30/hr',
    matchScore: 44,
    fitTier: 'Low-Fit',
    sponsorshipStatus: 'Rare',
    cptCompatible: false,
    optCompatible: false,
    h1bSponsor: false,
    matchReasons: ['Federal student trainee program for engineering majors'],
    warningFlags: [
      'Federal position — typically requires US citizenship',
      'Not CPT or OPT compatible for most positions',
      'International students rarely eligible for federal roles',
    ],
    recommendedAction:
      'Skip this role. Federal citizenship requirements disqualify most F-1 students.',
    postedDate: '2025-03-20',
    industry: 'Aerospace',
    experienceRequired: 'Internship',
    skills: ['Python', 'MATLAB', 'C++', 'Linux'],
    description:
      'Work on spacecraft systems and software for deep space exploration missions.',
    applicants: 890,
    engineeringDiscipline: 'Software/CS',
    roleFamily: 'campus job',
    sponsorshipSignal: 'Risky',
  },
  {
    id: 'opp-8',
    title: 'Data Scientist — AI Platform',
    company: 'Nvidia',
    companyInitials: 'NV',
    companyColor: '#76b900',
    location: 'Santa Clara, CA',
    remote: false,
    salaryRange: '$135k – $175k',
    matchScore: 86,
    fitTier: 'Realistic',
    sponsorshipStatus: 'Strong History',
    cptCompatible: true,
    optCompatible: true,
    h1bSponsor: true,
    matchReasons: [
      'Top H-1B sponsor — strong track record',
      'GPU/ML expertise is highly valued here',
      'STEM OPT extends your runway significantly',
      'Python and PyTorch are core to the role',
    ],
    warningFlags: [],
    recommendedAction: 'Strong strategic target. Apply within the next 48 hours.',
    postedDate: '2025-04-14',
    industry: 'Technology',
    experienceRequired: 'Entry Level',
    skills: ['Python', 'PyTorch', 'CUDA', 'Data Analysis'],
    description: 'Drive data-driven decisions on GPU performance and developer tooling.',
    applicants: 195,
    engineeringDiscipline: 'Data/AI/ML',
    roleFamily: 'entry-level',
    sponsorshipSignal: 'Better',
  },
];

export const mockStrategy: StrategyOutput = {
  overallReadiness: 78,
  summary:
    'You are in a strong position for the 2025 engineering career cycle. Your STEM OPT eligibility provides a 3-year runway, and your Software/CS discipline aligns well with high-sponsoring companies. Focus your energy on Realistic-tier internship and entry-level roles at Microsoft, Nvidia, and Stripe where your profile aligns most strongly.',
  insights: [
    {
      type: 'success',
      title: 'STEM OPT Advantage',
      body: 'Your STEM OPT eligibility extends your work authorization to 3 years post-graduation. Communicate this to recruiters — it reduces urgency around H-1B filing and makes you more attractive to companies evaluating international hires.',
    },
    {
      type: 'warning',
      title: 'H-1B Timeline Pressure',
      body: 'H-1B cap season runs October 1 – March 31. To be covered by October 2025, your employer must file by late March. Close an offer before January of your target year.',
    },
    {
      type: 'success',
      title: '4 Realistic Engineering Targets Found',
      body: 'Microsoft, Google, Stripe, and Nvidia are confirmed H-1B sponsors with strong records. Concentrate 70% of application effort here for the best engineering career ROI.',
    },
    {
      type: 'info',
      title: 'Internship + Entry-Level Strategy',
      body: "Your preferred role families (internship, co-op, entry-level) are well-represented in the matched results. Target summer internships now to convert to full-time offers with H-1B sponsorship.",
    },
  ],
  timelineWarnings: [
    'OPT application must be submitted 90 days before graduation — do not miss this window',
    'H-1B cap lottery opens April 1 — employer must be ready to file immediately',
    'STEM OPT extension must be filed before standard OPT expires',
    'Cap-gap protection applies if H-1B is pending when OPT expires — understand your backup plan',
  ],
  skillGaps: [
    {
      skill: 'System Design',
      importance: 'Critical',
      suggestion:
        'Practice Grokking System Design or InterviewBit. Most SWE internship loops include 1–2 system design rounds.',
    },
    {
      skill: 'Distributed Systems',
      importance: 'High',
      suggestion:
        'Read "Designing Data-Intensive Applications" (Kleppmann). Directly relevant for Google/Microsoft interviews.',
    },
    {
      skill: 'CUDA / GPU Programming',
      importance: 'Medium',
      suggestion:
        'Nvidia and AI-focused roles increasingly value GPU expertise. One weekend tutorial on CUDA basics can differentiate your application.',
    },
  ],
  actionPlan: {
    thisWeek: [
      {
        label: 'Apply to Microsoft SWE II',
        description:
          'Tailor resume for TypeScript/Azure keywords. Apply via careers portal + LinkedIn.',
        done: false,
      },
      {
        label: 'Apply to Nvidia Data Scientist',
        description:
          'Highlight PyTorch + CUDA experience. Posted 2 days ago — act fast.',
        done: false,
      },
      {
        label: 'File OPT application with DSO',
        description:
          'Get I-20 endorsed and submit Form I-765 to USCIS immediately.',
        done: true,
      },
      {
        label: 'Request LinkedIn referral for Google',
        description: 'Reach out to 2–3 UIUC alumni at Google in Seattle/SF.',
        done: false,
      },
    ],
    thisMonth: [
      {
        label: 'Apply to Stripe Engineering Internship',
        description:
          'Strong CPT-compatible internship. Customize cover letter around payments/infrastructure work.',
        done: false,
      },
      {
        label: 'Complete 50 LeetCode problems',
        description: 'Focus on arrays, trees, and graphs. Target easy/medium.',
        done: false,
      },
      {
        label: 'Consult an immigration attorney',
        description:
          'Get a 30-min session to validate your CPT-to-OPT-to-H1B engineering career strategy.',
        done: false,
      },
      {
        label: 'Attend 2 engineering networking events',
        description: 'Prioritize SF and Seattle events; virtual is acceptable.',
        done: false,
      },
    ],
    threeMonths: [
      {
        label: 'Secure 2+ engineering internship or full-time offers',
        description:
          'Compare H-1B track records, not just salary, when choosing between offers.',
        done: false,
      },
      {
        label: 'Finalize employer for H-1B sponsorship',
        description:
          'Ensure company is ready to file in April H-1B cap window.',
        done: false,
      },
      {
        label: 'Close the CUDA/GPU skill gap',
        description:
          'Build one project demonstrating GPU programming to unlock Nvidia and AI infrastructure roles.',
        done: false,
      },
    ],
  },
};
