import { Opportunity, StudentProfile, StrategyOutput } from './types';

export const mockProfile: StudentProfile = {
  id: 'student-1',
  name: 'Priya Sharma',
  email: 'priya@university.edu',
  major: 'Computer Science',
  school: 'University of Illinois Urbana-Champaign',
  degreeLevel: 'Master',
  graduationDate: '2025-05-15',
  gpa: 3.8,
  currentVisa: 'F-1 (OPT)',
  optStartDate: '2025-06-01',
  stemEligible: true,
  sponsorshipNeeded: true,
  targetRoles: ['Software Engineer', 'ML Engineer', 'Data Scientist'],
  targetIndustries: ['Technology', 'FinTech', 'AI/ML'],
  skills: ['Python', 'TypeScript', 'React', 'PyTorch', 'AWS', 'SQL'],
  experienceLevel: 'Entry Level',
  preferredLocations: ['San Francisco, CA', 'Seattle, WA', 'New York, NY'],
  remotePreference: 'Hybrid',
  yearsOfExperience: 1,
};

export const mockOpportunities: Opportunity[] = [
  {
    id: 'opp-1',
    title: 'Software Engineer II',
    company: 'Microsoft',
    companyInitials: 'MS',
    companyColor: '#0078d4',
    location: 'Seattle, WA',
    remote: false,
    salaryRange: '$130k – $165k',
    matchScore: 94,
    fitTier: 'Realistic',
    sponsorshipStatus: 'Strong History',
    cptCompatible: true,
    optCompatible: true,
    h1bSponsor: true,
    matchReasons: [
      '8+ consecutive years of H-1B sponsorship',
      'MS in CS aligns with role requirements',
      'Strong Python and TypeScript fit',
      'Seattle is your top preferred location',
    ],
    warningFlags: [],
    recommendedAction: 'Apply immediately — this is your highest-confidence match.',
    postedDate: '2025-04-12',
    industry: 'Technology',
    experienceRequired: 'Entry Level',
    skills: ['TypeScript', 'Python', 'Azure', 'React'],
    description: 'Join a core product engineering team building tools used by millions.',
    applicants: 340,
  },
  {
    id: 'opp-2',
    title: 'ML Engineer',
    company: 'Google',
    companyInitials: 'G',
    companyColor: '#4285f4',
    location: 'San Francisco, CA',
    remote: false,
    salaryRange: '$155k – $210k',
    matchScore: 88,
    fitTier: 'Realistic',
    sponsorshipStatus: 'Strong History',
    cptCompatible: false,
    optCompatible: true,
    h1bSponsor: true,
    matchReasons: [
      'Top H-1B sponsor — sponsored 3,200+ in 2024',
      'PyTorch experience is a strong match',
      'STEM OPT eligibility extends runway by 2 years',
      'Your ML coursework aligns with JD',
    ],
    warningFlags: ['Highly competitive — 1,200+ applicants expected'],
    recommendedAction: 'Tailor your resume toward ML infrastructure work. Referral highly recommended.',
    postedDate: '2025-04-10',
    industry: 'Technology',
    experienceRequired: 'Entry Level',
    skills: ['Python', 'PyTorch', 'TensorFlow', 'Kubernetes'],
    description: 'Work on ML systems that power Google\'s core search and ads infrastructure.',
    applicants: 1240,
  },
  {
    id: 'opp-3',
    title: 'Data Scientist',
    company: 'Stripe',
    companyInitials: 'ST',
    companyColor: '#635bff',
    location: 'San Francisco, CA',
    remote: true,
    salaryRange: '$125k – $160k',
    matchScore: 82,
    fitTier: 'Realistic',
    sponsorshipStatus: 'Strong History',
    cptCompatible: true,
    optCompatible: true,
    h1bSponsor: true,
    matchReasons: [
      'Consistent H-1B sponsor for 6+ years',
      'FinTech aligns with your target industries',
      'SQL and Python are core requirements you meet',
      'Remote option suits flexible location preference',
    ],
    warningFlags: ['Interview process is rigorous — 5+ rounds'],
    recommendedAction: 'Strong fit. Prepare for statistical modeling take-home.',
    postedDate: '2025-04-08',
    industry: 'FinTech',
    experienceRequired: 'Entry Level',
    skills: ['Python', 'SQL', 'Statistics', 'dbt', 'Looker'],
    description: 'Help Stripe use data to reduce fraud and improve payment success rates.',
    applicants: 287,
  },
  {
    id: 'opp-4',
    title: 'Software Engineer',
    company: 'Airbnb',
    companyInitials: 'AB',
    companyColor: '#ff5a5f',
    location: 'San Francisco, CA',
    remote: true,
    salaryRange: '$120k – $155k',
    matchScore: 73,
    fitTier: 'Stretch',
    sponsorshipStatus: 'Occasional',
    cptCompatible: true,
    optCompatible: true,
    h1bSponsor: true,
    matchReasons: [
      'React and TypeScript experience is a match',
      'Remote role fits your location preference',
    ],
    warningFlags: [
      'Sponsorship is not guaranteed — case-by-case basis',
      'Team prefers 2+ years of industry experience',
    ],
    recommendedAction: 'Worth applying, but don\'t rely on this as a primary target. Follow up if no response in 2 weeks.',
    postedDate: '2025-04-05',
    industry: 'Technology',
    experienceRequired: 'Mid Level',
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL'],
    description: 'Build the infrastructure for Airbnb\'s host and guest-facing web products.',
    applicants: 520,
  },
  {
    id: 'opp-5',
    title: 'ML Research Engineer',
    company: 'OpenAI',
    companyInitials: 'OA',
    companyColor: '#10a37f',
    location: 'San Francisco, CA',
    remote: false,
    salaryRange: '$175k – $250k',
    matchScore: 68,
    fitTier: 'Stretch',
    sponsorshipStatus: 'Strong History',
    cptCompatible: false,
    optCompatible: true,
    h1bSponsor: true,
    matchReasons: [
      'Strong H-1B sponsor with clear immigration support',
      'PyTorch and ML background is relevant',
    ],
    warningFlags: [
      'Role requires PhD or equivalent research experience',
      'Extremely competitive — typically 0.1% acceptance rate',
      'Not CPT compatible based on role seniority',
    ],
    recommendedAction: 'Apply as a long-shot. Focus energy on higher-probability targets first.',
    postedDate: '2025-04-01',
    industry: 'AI/ML',
    experienceRequired: 'Senior',
    skills: ['Python', 'PyTorch', 'CUDA', 'Research', 'LLMs'],
    description: 'Contribute to foundational research on large language models and alignment.',
    applicants: 2100,
  },
  {
    id: 'opp-6',
    title: 'Backend Engineer',
    company: 'Robinhood',
    companyInitials: 'RH',
    companyColor: '#00c805',
    location: 'Menlo Park, CA',
    remote: false,
    salaryRange: '$115k – $145k',
    matchScore: 61,
    fitTier: 'Stretch',
    sponsorshipStatus: 'Occasional',
    cptCompatible: true,
    optCompatible: true,
    h1bSponsor: false,
    matchReasons: [
      'Python backend skills match',
      'FinTech industry aligns with your goals',
    ],
    warningFlags: [
      'No confirmed H-1B sponsorship history in public records',
      'Company is in growth-to-profitability phase — may freeze hiring',
      'H-1B sponsorship is not guaranteed',
    ],
    recommendedAction: 'Proceed with caution. Verify sponsorship policy directly in interview.',
    postedDate: '2025-03-28',
    industry: 'FinTech',
    experienceRequired: 'Entry Level',
    skills: ['Python', 'Go', 'PostgreSQL', 'Kafka'],
    description: 'Build reliable financial systems for Robinhood\'s trading infrastructure.',
    applicants: 410,
  },
  {
    id: 'opp-7',
    title: 'Software Engineer',
    company: 'Palantir',
    companyInitials: 'PL',
    companyColor: '#1a1a1a',
    location: 'New York, NY',
    remote: false,
    salaryRange: '$110k – $145k',
    matchScore: 44,
    fitTier: 'Low-Fit',
    sponsorshipStatus: 'Rare',
    cptCompatible: false,
    optCompatible: false,
    h1bSponsor: false,
    matchReasons: [
      'Technical skills partially match',
    ],
    warningFlags: [
      'Requires US citizenship or security clearance',
      'Not CPT or OPT compatible',
      'International students almost never hired for this team',
    ],
    recommendedAction: 'Skip this role. Work authorization requirements disqualify international students.',
    postedDate: '2025-03-20',
    industry: 'Technology',
    experienceRequired: 'Entry Level',
    skills: ['Java', 'Python', 'Spark', 'Foundry'],
    description: 'Work on data platforms used by government and enterprise clients.',
    applicants: 890,
  },
  {
    id: 'opp-8',
    title: 'Data Scientist',
    company: 'Nvidia',
    companyInitials: 'NV',
    companyColor: '#76b900',
    location: 'Santa Clara, CA',
    remote: false,
    salaryRange: '$135k – $175k',
    matchScore: 86,
    fitTier: 'Realistic',
    sponsorshipStatus: 'Strong History',
    cptCompatible: true,
    optCompatible: true,
    h1bSponsor: true,
    matchReasons: [
      'Top H-1B sponsor — strong track record',
      'GPU/ML expertise is highly valued here',
      'STEM OPT extends your runway significantly',
      'Python and PyTorch are core to the role',
    ],
    warningFlags: [],
    recommendedAction: 'Strong strategic target. Apply within the next 48 hours.',
    postedDate: '2025-04-14',
    industry: 'Technology',
    experienceRequired: 'Entry Level',
    skills: ['Python', 'PyTorch', 'CUDA', 'Data Analysis'],
    description: 'Drive data-driven decisions on GPU performance and developer tooling.',
    applicants: 195,
  },
];

export const mockStrategy: StrategyOutput = {
  overallReadiness: 78,
  summary: 'You are in a strong position for the 2025 summer recruiting cycle. Your STEM OPT eligibility provides a 3-year runway, which significantly expands your sponsorship options. Focus your energy on the Realistic tier — Microsoft, Google, Stripe, and Nvidia are your highest-probability targets. Avoid spending time on roles that are CPT/OPT incompatible or that have no H-1B history.',
  insights: [
    {
      type: 'success',
      title: 'STEM OPT Advantage',
      body: 'Your STEM OPT eligibility extends your work authorization by 24 months beyond standard OPT, giving you a total 3-year runway. This is your biggest strategic asset — emphasize it with sponsors who value extended trial periods before H-1B filing.',
    },
    {
      type: 'warning',
      title: 'Timeline Urgency',
      body: 'H-1B cap season runs October 1 – March 31. To be covered for October 2025 start, your employer must file by late March 2025. If you\'re on OPT starting June 2025, you have one filing cycle before you need a cap-exempt or STEM extension bridge.',
    },
    {
      type: 'info',
      title: 'Priority Targets Identified',
      body: '4 of your 8 matches are Realistic-tier with confirmed H-1B history. Concentrate 70% of application effort on these 4 companies for the highest ROI.',
    },
    {
      type: 'success',
      title: 'Strong Skills Alignment',
      body: 'Python, TypeScript, and PyTorch appear across 87% of your Realistic matches. Your technical profile is well-calibrated to current market demand.',
    },
  ],
  timelineWarnings: [
    'OPT application should be filed 90 days before graduation (February 2025)',
    'H-1B cap lottery opens April 1 — employer must be ready to file immediately',
    'STEM OPT extension must be filed before standard OPT expires',
    'Cap-gap protection applies if H-1B is pending when OPT expires — understand your backup',
  ],
  skillGaps: [
    {
      skill: 'System Design',
      importance: 'Critical',
      suggestion: 'Practice Grokking System Design or InterviewBit. Most senior SWE loops include 1–2 system design rounds.',
    },
    {
      skill: 'Distributed Systems',
      importance: 'High',
      suggestion: 'Read "Designing Data-Intensive Applications" (Kleppmann). Directly relevant for Google/Microsoft rounds.',
    },
    {
      skill: 'Go / Golang',
      importance: 'Medium',
      suggestion: 'Several FinTech targets use Go for backend services. One weekend of tutorials would improve positioning.',
    },
  ],
  actionPlan: {
    thisWeek: [
      { label: 'Apply to Microsoft SWE II', description: 'Tailor resume for TypeScript/Azure keywords. Apply via careers portal + LinkedIn.', done: false },
      { label: 'Apply to Nvidia Data Scientist', description: 'Highlight PyTorch + CUDA experience. Posted 2 days ago — act fast.', done: false },
      { label: 'File OPT application with DSO', description: 'Get I-20 endorsed and submit Form I-765 to USCIS immediately.', done: true },
      { label: 'Request LinkedIn referral for Google', description: 'Reach out to 2–3 UIUC alumni at Google in Seattle/SF.', done: false },
    ],
    thisMonth: [
      { label: 'Complete 50 LeetCode problems', description: 'Focus on arrays, trees, and graphs. Target easy/medium.', done: false },
      { label: 'Apply to Stripe and OpenAI', description: 'Customize cover letter around data impact stories for Stripe.', done: false },
      { label: 'Consult an immigration attorney', description: 'Get a 30-min session to validate your CPT-to-OPT-to-H1B strategy.', done: false },
      { label: 'Attend 2 tech networking events', description: 'Prioritize SF and Seattle events; virtual is acceptable.', done: false },
    ],
    threeMonths: [
      { label: 'Secure 3+ offers from Realistic tier', description: 'Compare H-1B track records, not just salary, when choosing.', done: false },
      { label: 'Finalize employer for H-1B sponsorship', description: 'Ensure company is ready to file in April\'s H-1B cap window.', done: false },
      { label: 'Build side project in Go', description: 'Ship one small project to close the Golang gap for FinTech targets.', done: false },
    ],
  },
};
